// Curated list of keyboard-relevant icons from Lucide
// Organized by category for easier browsing
export const KEYBOARD_ICONS = {
  arrows: [
    'ArrowUp',
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'ChevronUp',
    'ChevronDown',
    'ChevronLeft',
    'ChevronRight',
    'ChevronsUp',
    'ChevronsDown',
    'MoveUp',
    'MoveDown',
    'CornerUpLeft',
    'CornerUpRight',
    'CornerDownLeft',
    'CornerDownRight',
  ],
  media: [
    'Play',
    'Pause',
    'SkipBack',
    'SkipForward',
    'Rewind',
    'FastForward',
    'Volume',
    'Volume1',
    'Volume2',
    'VolumeX',
    'Mic',
    'MicOff',
    'Music',
    'Headphones',
  ],
  actions: [
    'Copy',
    'Clipboard',
    'ClipboardCopy',
    'ClipboardPaste',
    'Scissors',
    'Undo',
    'Undo2',
    'Redo',
    'Redo2',
    'Save',
    'Trash',
    'Trash2',
    'Edit',
    'Edit2',
    'Pencil',
  ],
  navigation: [
    'Home',
    'Search',
    'Menu',
    'MoreHorizontal',
    'MoreVertical',
    'Grid',
    'List',
    'Maximize',
    'Minimize',
    'Maximize2',
    'Minimize2',
    'ZoomIn',
    'ZoomOut',
    'RefreshCw',
  ],
  system: [
    'Power',
    'Settings',
    'Cog',
    'Lock',
    'Unlock',
    'Key',
    'Shield',
    'Eye',
    'EyeOff',
    'Bell',
    'BellOff',
    'Wifi',
    'WifiOff',
    'Bluetooth',
  ],
  text: [
    'Type',
    'Bold',
    'Italic',
    'Underline',
    'Strikethrough',
    'AlignLeft',
    'AlignCenter',
    'AlignRight',
    'AlignJustify',
    'Indent',
    'Outdent',
    'ListOrdered',
    'TextCursor',
  ],
  symbols: [
    'Plus',
    'Minus',
    'X',
    'Check',
    'Equal',
    'Hash',
    'AtSign',
    'Percent',
    'Star',
    'Heart',
    'Bookmark',
    'Flag',
    'Tag',
    'Circle',
    'Square',
    'Triangle',
  ],
  apps: [
    'Mail',
    'Calendar',
    'Clock',
    'Calculator',
    'Camera',
    'Image',
    'Video',
    'FileText',
    'Folder',
    'Download',
    'Upload',
    'Share',
    'Link',
    'ExternalLink',
    'Globe',
    'Terminal',
    'Code',
  ],
  gaming: [
    'Gamepad',
    'Gamepad2',
    'Joystick',
    'Trophy',
    'Target',
    'Swords',
    'Zap',
    'Flame',
    'Sparkles',
    'Crosshair',
  ],
} as const;

// Flatten all icons into a single array
export const ALL_ICONS = Object.values(KEYBOARD_ICONS).flat();

// Get category for an icon
export const getIconCategory = (iconName: string): string | undefined => {
  for (const [category, icons] of Object.entries(KEYBOARD_ICONS)) {
    if ((icons as readonly string[]).includes(iconName)) {
      return category;
    }
  }
  return undefined;
};
